;;;; test/matcher/test_mr_tree.lisp -- MR-TREE unit tests (inside Maxima).
;;;; Run: maxima --very-quiet -b test/matcher/test_mr_tree.mac

(defpackage :mr-tree-test (:use :cl :mr-match :mr-tree) (:export #:run))
(in-package :mr-tree-test)

(defvar *passed* 0)
(defvar *failed* 0)

(defun check (name ok &optional detail)
  (if ok
      (progn (incf *passed*) (format t "  PASS: ~a~%" name))
      (progn (incf *failed*) (format t "  FAIL: ~a~@[~%    ~a~]~%" name detail))))

(defun conv (s) (max->tree (maxima-form s)))

(defmacro check-conv (s expected)
  `(let ((got (conv ,s)) (want (canonicalize (read-tree ,expected))))
     (check (format nil "max->tree ~a" ,s) (equal got want)
            (format nil "got ~a want ~a" (tree-string got) (tree-string want)))))

(defun round-trips-p (s)
  (let* ((e (maxima-form s)) (back (tree->max (max->tree e))))
    (values (maxima::alike1 e back) back)))

(defun test-table ()
  (format t "--- head table ---~%")
  (let ((table (head-table)))
    (check "one entry per (head, arity) of the probe-02 table" (= (length table) 45) (length table))
    (flet ((op (head arity) (third (find-if (lambda (r) (and (string= (symbol-name (first r)) head)
                                                             (= (second r) arity)))
                                            table))))
      (check "abs -> mabs" (eq (op "Abs" 1) 'maxima::mabs))
      (check "factorial -> mfactorial" (eq (op "Factorial" 1) 'maxima::mfactorial))
      (check "Gamma/2 -> %gamma_incomplete" (eq (op "Gamma" 2) 'maxima::%gamma_incomplete)))))

(defun test-max->tree ()
  (format t "--- max->tree ---~%")
  (check-conv "a+b*x" "(Plus a (Times b x))")
  (check-conv "x^(1/3)" "(Power x 1/3)")
  (check-conv "sqrt(x)" "(Power x 1/2)")
  (check-conv "1/x" "(Power x -1)")
  (check-conv "-x" "(Times -1 x)")
  (check-conv "exp(2*x)" "(Power E (Times 2 x))")
  (check-conv "%pi*x" "(Times Pi x)")
  (check-conv "A*x" "(Times A x)")
  (check-conv "log(x)" "(Log x)")
  (check-conv "abs(x)" "(Abs x)")
  (check-conv "x!" "(Factorial x)")
  (check-conv "gamma_incomplete(a,x)" "(Gamma a x)")
  (check-conv "li[2](x)" "(PolyLog 2 x)")
  (check-conv "psi[1](x)" "(PolyGamma 1 x)")
  (check-conv "0.1*x" "(Times 0.1d0 x)")
  (check-conv "1.5b0*x" "(Times 1.5d0 x)")
  (check-conv "2*%i*x" "(Times #C(0 2) x)")
  (check-conv "1+%i" "#C(1 1)")
  (check-conv "%i" "#C(0 1)")
  (check-conv "b*a+c" "(Plus c (Times a b))")
  (let ((got (conv "foo(x)")))
    (check "unknown function -> MX_ head" (and (consp got) (search "MX_" (symbol-name (car got))))
           (tree-string got)))
  (check-conv "polylog(2,x)" "(PolyLog 2 x)")
  ;; the dispatcher converts integrands and bindings, which can be CRE or boolean
  (check-conv "rat(a+b*x)" "(Plus a (Times b x))")
  ;; (a CRE numerator is an expanded polynomial)
  (check-conv "rat((1+x)^2/(2*y))" "(Times 1/2 (Plus 1 (Power x 2) (Times 2 x)) (Power y -1))")
  (check-conv "true" "True")
  (check-conv "false" "False")
  (check "tree->max True/False -> the Maxima booleans"
         (and (eq (tree->max (sym "True")) t) (null (tree->max (sym "False")))))
  (check "maxima-name restores case" (equal (list (maxima-name 'maxima::$mm_sin) (maxima-name 'maxima::|$a|)
                                                  (maxima-name 'maxima::%sin))
                                            '("mm_sin" "A" "sin")))
  (let ((*unknown-head-hook* (lambda (op)
                               (let ((n (maxima-name op)))
                                 (and (> (length n) 3) (string= "mm_" n :end2 3) (sym (subseq n 3)))))))
    (check-conv "mm_Foo(x)" "(Foo x)")
    (check-conv "mm_sin(x)" "(sin x)")))

(defun test-round-trip ()
  (format t "--- tree->max round trip ---~%")
  (dolist (s '("a+b*x" "(a+b*x)^m*(c+d*x)^n" "x/(a+b*x)" "2*%i*x" "1+%i" "li[2](x)" "psi[1](x)"
               "sin(x)^2*log(c*x)" "A*x" "abs(x)" "x!" "0.1*x" "exp(2*x)" "foo(x,y)"
               "gamma_incomplete(a,x)" "sqrt(1-x^2)" "%pi*x"))
    (multiple-value-bind (ok back) (round-trips-p s)
      (check (format nil "round trip ~a" s) ok (format nil "back ~s" back)))))

(defun run ()
  (setf *passed* 0 *failed* 0)
  (test-table)
  (test-max->tree)
  (test-round-trip)
  (format t "Results: ~a passed, ~a failed~%" *passed* *failed*)
  (finish-output))
