#!/usr/bin/env python3
"""probes/gtq/make_census_overlay.py OUT.mac -- write the GtQ-family census
overlay (RUNTIME, probe only; the tree's rule files are untouched).

Every generated `_mr_cond_*` definition of rules/class*/*.mac holding a real
comparison is(A op B), op in > < >= <= (the generator's CMP_OPS emission for
GtQ/LtQ/GeQ/LeQ, generator/generate_rules.py, plus the raw-relation chains),
is re-emitted with each such is(A op B) replaced by

    %mr_gtq_W("op", A, B, "<key> r<n> s<k>[ neg]")

(k = the site's index in that cond, `neg` = the is() is the whole argument of
not(...)).  %mr_gtq_W (probes/gtq/census-wrapper.mac) computes the current
value, (F) and (R), logs a disagreement, and returns the arm's value.
Loaded after mr_load_all(), it redefines those functions (the rule records
hold the cond by NAME, so the redefinition takes effect).  Technique from
probes/class-ports/make_fix_b_overlay.py (branch class6-attribution)."""
import glob, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
IS = re.compile(r"(?<![A-Za-z0-9_%])is\(")


def top_bool(s):
    """True when s has a top-level `and` / `or` (a boolean expression, not a
    single comparison: the raw-relation conds, e.g. 1_1_3_7 r40's
    is(%mr_neQ(..) and q - n >= 0 and ..) = true, a With-local condition)."""
    depth, i = 0, 0
    while i < len(s):
        c = s[i]
        if c == '"':
            i = s.index('"', i + 1)
        elif c in "([":
            depth += 1
        elif c in ")]":
            depth -= 1
        elif depth == 0 and re.match(r"\s(and|or)\s", s[i:i + 5]):
            return True
        i += 1
    return False


def top_cmp(s):
    if top_bool(s):
        return None
    depth, i = 0, 0
    while i < len(s):
        c = s[i]
        if c == '"':
            i = s.index('"', i + 1)
        elif c in "([":
            depth += 1
        elif c in ")]":
            depth -= 1
        elif depth == 0 and c in "<>":
            op = s[i:i + 2] if s[i + 1:i + 2] == "=" else c
            return op, s[:i], s[i + len(op):]
        i += 1
    return None


def rewrite(body, handle, counter):
    out, i = [], 0
    while True:
        m = IS.search(body, i)
        if not m:
            out.append(body[i:]); break
        out.append(body[i:m.start()])
        j, depth = m.end(), 1
        while depth:
            if body[j] == "(": depth += 1
            elif body[j] == ")": depth -= 1
            j += 1
        inner = rewrite(body[m.end():j - 1], handle, counter)
        cmp = top_cmp(inner)
        if cmp:
            counter[0] += 1
            neg = body[max(0, m.start() - 4):m.start()] == "not(" and body[j:j + 1] == ")"
            op, a, b = cmp
            h = f"{handle} s{counter[0]}" + (" neg" if neg else "")
            out.append(f'%mr_gtq_W("{op}", {a.strip()}, {b.strip()}, "{h}")')
        else:
            out.append(f"is({inner})")
        i = j
    return "".join(out)


def main():
    dest = sys.argv[1]
    defs = sites = 0
    out = []
    for path in sorted(glob.glob(os.path.join(ROOT, "rules", "class*", "*.mac"))):
        text = open(path).read()
        for m in re.finditer(r"^_mr_cond_(\S+)_r(\d+)\(mm, x\) := .*?\$\s*$", text, re.M | re.S):
            d = m.group(0).rstrip()
            if "\n_mr_" in d:
                d = d.split("\n_mr_")[0]
            if not d.endswith("$"):
                raise SystemExit(f"unterminated cond definition in {path}: {d[:80]}")
            counter = [0]
            f = rewrite(d, f"{m.group(1)} r{m.group(2)}", counter)
            if counter[0]:
                defs += 1; sites += counter[0]
                out.append(f)
    with open(dest, "w") as fh:
        fh.write(f"/* generated by probes/gtq/make_census_overlay.py: {defs} cond "
                 f"definitions, {sites} comparison sites -> %mr_gtq_W. RUNTIME "
                 "OVERLAY, probe only. */\n")
        fh.write("\n".join(out) + "\n")
        fh.write(f'print("GTQ census overlay loaded: {defs} defs {sites} sites")$\n')
    print(defs, sites)


if __name__ == "__main__":
    main()
