;;; probes/matcher/02-controls.lisp -- controls for two round-trip findings
;;; (probes/matcher/02-FINDINGS.md):
;;;  U*  the wrong (UNSOUND) bindings mma4max returns for the
;;;      (a_.+b_.*F[u_])^p_. family, re-matched with the witness symbols as
;;;      generated and with every symbol renamed: a result that depends on the
;;;      names would be an artifact of the witnesses.
;;;  H*  pattern-variable heads F_[..] and compound heads Derivative[n_][f_][..]
;;;      placed at the top, under Times, under Plus, under Power: the round
;;;      trip's misses all carry such a head.
;;; Data: generated by `python3 probes/matcher/02-roundtrip.py controls` (the
;;; U patterns/targets come from the pinned rules through 02-roundtrip.py's
;;; witness construction; H cases are synthetic, expectations hand-derived
;;; from Mathematica semantics).  Driver: 02-controls.run.

(in-package :cl-user)

(defun controls-run (mode)
  (let ((*print-pretty* nil) (*print-right-margin* 1000000))
    (dolist (c *controls*)
      (destructuring-bind (id label pat tree note) c
        (fresh-env)
        (let* ((p (prepare-pattern (rt-read pat)))
               (m (with-cap (5)
                    (multiple-value-list
                     (match-once p (list (mm-sym "Int") (rt-read tree) (mm-sym "x")) #'mma::truth)))))
          (format t "~&CONTROL ~a ~a  ~a~%  target: ~a~%  expect: ~a~%  result: ~a~%"
                  mode id label tree note
                  (cond ((eq m :timeout) "timeout")
                        ((eq (car m) :error) (format nil "error ~a" (second m)))
                        (t (format nil "matched=~a bindings=~a" (first m)
                                   (rt-sxs (mapcar (lambda (b) (list (car b) (cdr b))) (second m))))))))))))
