#!/usr/bin/env python3
"""probes/class-ports/make_fix_b_overlay.py -- write
probes/class-ports/fix-B-gtq-overlay.mac, a RUNTIME overlay (probe only):
every generated `_mr_cond_*` definition of rules/class*/*.mac that contains
a real comparison is(A op B), op in > < >= <= (the generator's CMP_OPS
emission for GtQ/LtQ/GeQ/LeQ), re-emitted with each such is(...) replaced
by (is(...) = true) -- the two-valued reading: undecided reads False, so
Not[GtQ[a,0]] on a symbol reads True as in Rubi. Loaded after the core,
it redefines those functions; the tree's rule files are untouched. This is
the textual image of the one-line generator change proposed in the report
(generate_rules.py CMP_OPS: return f"(is({a} {op} {b}) = true)")."""
import glob, os, re, sys
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CMP = re.compile(r"(>=|<=|>|<)")

def top_level_cmp(s):
    depth = 0; i = 0
    while i < len(s):
        ch = s[i]
        if ch in "([": depth += 1
        elif ch in ")]": depth -= 1
        elif depth == 0 and ch in "<>":
            return True
        elif ch == '"':
            i = s.index('"', i + 1)
        i += 1
    return False

def fix(body):
    out = []; i = 0; n = 0
    while True:
        m = re.compile(r"(?<![A-Za-z0-9_%])is\(").search(body, i)
        if not m:
            out.append(body[i:]); break
        out.append(body[i:m.start()])
        j = m.end(); depth = 1
        while depth:
            if body[j] == "(": depth += 1
            elif body[j] == ")": depth -= 1
            j += 1
        inner = body[m.end():j - 1]
        inner_fixed, k = fix(inner)
        n += k
        if top_level_cmp(inner) and not re.match(r"\s*=\s*true", body[j:]):
            out.append(f"(is({inner_fixed}) = true)"); n += 1
        else:
            out.append(f"is({inner_fixed})")
        i = j
    return "".join(out), n

defs = 0; sites = 0; out = []
for path in sorted(glob.glob(os.path.join(ROOT, "rules", "class*", "*.mac"))):
    text = open(path).read()
    for m in re.finditer(r"^(_mr_cond_\S+\(mm, x\) := .*?)\$\s*$", text, re.M | re.S):
        d = m.group(1)
        if "\n_mr_" in d:
            # a non-greedy multi-line match must stay within one definition
            d = d.split("\n_mr_")[0]
        f, k = fix(d)
        if k:
            defs += 1; sites += k
            out.append(f + "$")
hdr = (f"/* generated by probes/class-ports/make_fix_b_overlay.py: {defs} cond "
       f"definitions, {sites} comparison sites rewritten is(A op B) -> "
       f"(is(A op B) = true). RUNTIME OVERLAY, probe only. */\n")
open(os.path.join(ROOT, "probes", "class-ports", "fix-B-gtq-overlay.mac"), "w").write(
    hdr + "\n".join(out) + '\nprint("FIX-B overlay loaded")$\n')
print(defs, sites)
