#!/usr/bin/env python3
"""probes/class-ports/class1/make_table_overlay.py -- write
class1/overlay-base-table.mac: on the class-ports core, restrict
mr_rule_table (as a literal list of class-ports handles) to the records (key, rN) that the master core's table holds,
in the class-ports table order (asserted equal to the master order). The
class-ports CODE (utilities, dispatcher, tree, renames, FreeFactors) stays;
only the 3,779 added records leave the walk.
Inputs: work/c1-table-base.txt, work/c1-table-new.txt (dump_table.mac output
on each core)."""
import os, re
H = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def rd(p):
    return [tuple(l.split()[1:6]) for l in open(os.path.join(H, p)) if l.startswith("TBL ")]
base = rd("work/c1-table-base.txt"); new = rd("work/c1-table-new.txt")
bset = {(k, n): (t, g) for _, k, n, t, g in base}
hand = {tuple(l.split()[2:4]): l.split()[6] for l in open(os.path.join(H, "work/c1-table-new.txt")) if l.startswith("TBL ")}
keep = [(hand[(k, n)], k, n) for p, k, n, t, g in new if (k, n) in bset]
assert [(k, n) for _, k, n in keep] == [(k, n) for _, k, n, _, _ in base], "order differs"
# the tail/general marks agree on the kept records
newmarks = {(k, n): (t, g) for _, k, n, t, g in new}
diff = [(k, n) for k, n in bset if bset[(k, n)] != newmarks[(k, n)]]
print("kept", len(keep), "of", len(new), "; mark differences:", diff)
with open(os.path.join(H, "class1/overlay-base-table.mac"), "w") as f:
    f.write("/* generated by class1/make_table_overlay.py: the class-ports table restricted\n"
            "   to the master core's %d records, in order */\n" % len(keep))
    f.write("mr_rule_table : [" + ",".join(str(p) for p, _, _ in keep) + "]$\n")
